/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CacheableOutputDataSchema {
  CacheableInputData_id: number;
  cachedDate: string;
  content: string;
  id: number;
  sha256: string;
  size: number;
  [k: string]: unknown;
}
