/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CacheableInputDataSchema {
  cachedDate: string;
  id: number;
  owner_id?: number;
  sha256: string;
  size: number;
  sourcePath: string;
  [k: string]: unknown;
}
