/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * json schema referenced by data in CacheableDataWithSchema
 */
export interface JsonSchemaRecordSchema {
  content: string;
  createdAt: string;
  description: string;
  id: number;
  sha256: string;
  [k: string]: unknown;
}
